######################################################################
# Automatically generated by qmake (3.0) Tue Dec 1 16:49:47 2020
######################################################################

TEMPLATE = app
TARGET = apothesis

QT-=gui core
QMAKE_CXXFLAGS += -std=c++17
CONFIG += debug_and_release
QMAKE_CXXFLAGS_RELEASE = -O0 -g -ffloat-store
QMAKE_CXXFLAGS_DEBUG = -O0 -g -ffloat-store
CONFING -= qt

INCLUDEPATH += . \
	 ./src \
         ./src/lattice \
         ./src/microprocesses \
         ./src/macroprocesses \
         ./src/IO \
         ./src/error

# Input
HEADERS += ./src/apothesis.h \
           ./src/IO/io.h \
           ./src/IO/cml_reader.h \
           ./src/IO/xyz_reader.h \
           ./src/lattice/SimpleCubic.h \
           ./src/microprocesses/adsorption.h \
           ./src/extLibs/random_generator.h \
           ./src/extLibs/randomc.h \
           ./src/pointers.h \
           ./src/microprocesses/reaction.h \
           ./src/properties.h \
           ./src/register.h \
           ./src/error/errorhandler.h \
           ./src/lattice/FCC.h \
           ./src/lattice/lattice.h \
           ./src/lattice/site.h \
           ./src/microprocesses/abstract_process.h \
           ./src/microprocesses/desorption.h \
           ./src/microprocesses/diffusion.h \
           ./src/microprocesses/factory_process.h \
           ./src/microprocesses/io.h \
           ./src/microprocesses/parameters.h \
           ./src/microprocesses/process.h \
           ./src/microprocesses/adsorption_perform.h \
           ./src/microprocesses/adsorption_rules.h \
           ./src/microprocesses/adsorption_types.h \
           ./src/microprocesses/desorption_perform.h \
           ./src/microprocesses/desorption_rules.h \
           ./src/microprocesses/desorption_types.h \
           ./src/microprocesses/diffusion_perform.h \
           ./src/microprocesses/diffusion_rules.h \
           ./src/microprocesses/diffusion_types.h \
           ./src/lattice/HCP.h \
           ./src/lattice/diamond.h \
           ./src/macroprocesses/ald.h \
           ./src/macroprocesses/ale.h \
           ./src/macroprocesses/catalysis.h \
           ./src/macroprocesses/cvd.h \
           ./src/macroprocesses/etching.h \
           ./src/macroprocesses/macroprocess.h \
           ./src/macroprocesses/pvd.h

SOURCES += ./src/apothesis.cpp \
           ./src/IO/io.cpp \
           ./src/IO/cml_reader.cpp \
           ./src/IO/xyz_reader.cpp \
           ./src/extLibs/mersenne.cpp \
           ./src/extLibs/random_generator.cpp \
           ./src/lattice/SimpleCubic.cpp \
           ./src/lattice/lattice.cpp \
           ./src/main.cpp \
           ./src/microprocesses/abstract_process.cpp \
           ./src/microprocesses/reaction.cpp \
           ./src/properties.cpp \
           ./src/error/errorhandler.cpp \
           ./src/lattice/FCC.cpp \
           ./src/lattice/site.cpp \
           ./src/microprocesses/adsorption.cpp \
           ./src/microprocesses/desorption.cpp \
           ./src/microprocesses/diffusion.cpp \
           ./src/microprocesses/factory_process.cpp \
           ./src/microprocesses/parameters.cpp \
           ./src/microprocesses/process.cpp \
           ./src/microprocesses/adsorption_perform.cpp \
           ./src/microprocesses/adsorption_rules.cpp \
           ./src/microprocesses/adsorption_types.cpp \
           ./src/microprocesses/desorption_perform.cpp \
           ./src/microprocesses/desorption_rules.cpp \
           ./src/microprocesses/desorption_types.cpp \
           ./src/microprocesses/diffusion_perform.cpp \
           ./src/microprocesses/diffusion_rules.cpp \
           ./src/microprocesses/diffusion_types.cpp \
           ./src/lattice/HCP.cpp \
           ./src/lattice/diamond.cpp \
           ./src/macroprocesses/ald.cpp \
           ./src/macroprocesses/ale.cpp \
           ./src/macroprocesses/catalysis.cpp \
           ./src/macroprocesses/cvd.cpp \
           ./src/macroprocesses/etching.cpp \
           ./src/macroprocesses/macroprocess.cpp \
           ./src/macroprocesses/pvd.cpp
